#!/usr/bin/env bash

#  execute the test -- you would most likely execute on submitted file
#  for example: cppcheck ../student_file.h <options>

# src code references
source='cppcheck.cpp
  ../redirect_io.h 
  ../check_hidden_heap.h
  ../lazy_hash_table.h
  '

cppcheck ${source} -x c++ --enable=all --verbose --error-exitcode=1 --suppressions-list=suppressions.txt